function incrementX(obj) {
    return 1 + obj.x;
}
incrementX({x: 42}); 


// [generated bytecode for function: binding]
// Parameter count 2
// Frame size 32
//  3203 E> 0000014C6C4366EA @    0 : a0                StackCheck
//  3220 S> 0000014C6C4366EB @    1 : 13 00 00          LdaGlobal [0], [0]
//          0000014C6C4366EE @    4 : 26 fa             Star r1
//  3229 E> 0000014C6C4366F0 @    6 : 5b fa 02 02       CallUndefinedReceiver1 r1, a0, [2]
//          0000014C6C4366F4 @   10 : 26 02             Star a0
//  3261 S> 0000014C6C4366F6 @   12 : 1b 04             LdaImmutableCurrentContextSlot [4]
//          0000014C6C4366F8 @   14 : a5 01             ThrowReferenceErrorIfHole [1]
//          0000014C6C4366FA @   16 : 26 fa             Star r1
//          0000014C6C4366FC @   18 : 25 02             Ldar a0
//  3271 E> 0000014C6C4366FE @   20 : 29 fa 04          LdaKeyedProperty r1, [4]
//          0000014C6C436701 @   23 : 26 fb             Star r0
//  3287 S> 0000014C6C436703 @   25 : 70 07             TestTypeOf #7
//          0000014C6C436705 @   27 : 93 3a             JumpIfTrue [58] (0000014C6C43673F @ 85)
//  3326 S> 0000014C6C436707 @   29 : 1b 04             LdaImmutableCurrentContextSlot [4]
//          0000014C6C436709 @   31 : a5 01             ThrowReferenceErrorIfHole [1]
//          0000014C6C43670B @   33 : 26 fa             Star r1
//          0000014C6C43670D @   35 : 19 ff 06 01       LdaImmutableContextSlot <context>, [6], [1]
//          0000014C6C436711 @   39 : 26 f8             Star r3
//  3353 E> 0000014C6C436713 @   41 : 5b f8 02 06       CallUndefinedReceiver1 r3, a0, [6]
//          0000014C6C436717 @   45 : 26 f8             Star r3
//  3351 E> 0000014C6C436719 @   47 : 2e fa 02 08       StaKeyedProperty r1, a0, [8]
//          0000014C6C43671D @   51 : 27 f8 fb          Mov r3, r0
//  3381 S> 0000014C6C436720 @   54 : 19 ff 11 01       LdaImmutableContextSlot <context>, [17], [1]
//          0000014C6C436724 @   58 : a5 02             ThrowReferenceErrorIfHole [2]
//          0000014C6C436726 @   60 : 26 f9             Star r2
//  3396 E> 0000014C6C436728 @   62 : 28 f9 03 0a       LdaNamedProperty r2, [3], [10]
//          0000014C6C43672C @   66 : 26 fa             Star r1
//          0000014C6C43672E @   68 : 12 04             LdaConstant [4]
//          0000014C6C436730 @   70 : 26 f8             Star r3
//          0000014C6C436732 @   72 : 25 02             Ldar a0
//  3412 E> 0000014C6C436734 @   74 : 75                ToString
//          0000014C6C436735 @   75 : 32 f8 0c          Add r3, [12]
//          0000014C6C436738 @   78 : 26 f8             Star r3
//  3396 E> 0000014C6C43673A @   80 : 57 fa f9 f8 0d    CallProperty1 r1, r2, r3, [13]
//  3437 S> 0000014C6C43673F @   85 : 25 fb             Ldar r0
//  3448 S> 0000014C6C436741 @   87 : a4                Return
// Constant pool (size = 5)
// Handler Table (size = 0)
// [generated bytecode for function: startup]
// Parameter count 1
// Frame size 440