function add(params) {
    var a = 10;
    var b = 20;
    var c = a + b;
    console.log(c);
}
add()
// node --print-bytecode .\simple.js


// Frame size 24
//     0 E> 000000A099721DC2 @    0 : a0                StackCheck 
//    54 S> 000000A099721DC3 @    1 : 7c 00 00 00       CreateClosure [0], [0], #0        
//          000000A099721DC7 @    5 : 26 fa             Star r1
//  1228 E> 000000A099721DC9 @    7 : 13 01 01          LdaGlobal [1], [1]
//          000000A099721DCC @   10 : 26 f9             Star r2
//  1227 E> 000000A099721DCE @   12 : 5b fa f9 03       CallUndefinedReceiver1 r1, r2, [3]
//          000000A099721DD2 @   16 : 26 fb             Star r0
//  1235 S> 000000A099721DD4 @   18 : a4                Return 
// Constant pool (size = 2)
// Handler Table (size = 0)
// [generated bytecode for function: ]
// Parameter count 2
// Frame size 64